### ISSUE TITLE
Exposing the Kafka Yammer metrics to Spring Boot Actuator

### ISSUE THREAD

**Issue by dmachlin** [spring-projects/spring-kafka#127]
Hi,
It would be great to automatically expose all of Kafka's metrics to Spring's metrics via spring boot actuator.
Do you know of a project that enables this?
If this isn't possible out-of-the-box, do you think it would be a good addition to this project?

**Comment by artembilan** [comment]
We really are going to implement Spring Boot auto-configuration in the next `1.1` version.
I think this Kafka Yammer metrics would be a good addition into Boot Actuator as well.

We are not sure yet when the solution will have place: in this project directly or in the next Spring Boot `1.5` iteration, but we definitely will come back to the nice "Convention on Configuration" universe.

**Comment by stepio** [comment]
Hi,

I've published my implementation of this here:
https://github.com/stepio/spring-actuator-kafka
Short description is also provided. I've already integrated this into my project - looks good as of now.

@artembilan @garyrussell 
Again, I'm not sure that it's wise to keep this project separately. So I'd like to merge it to spring-kafka or spring-boot - what do you think?

**Comment by artembilan** [comment]
Hello, @stepio !

Thank you for letting to know! That's great to have such a good progress :smile: .

Well, for now I don't have a proper answer for you, if it may move to Spring Boot...
I'd be fine to merge your cool work into Spring Kafka directly, but we really should decide here in our team what would be better.

@garyrussell is on PTO until the next week and we still don't have the proper scope for the next `1.1` iteration.

So, stay tuned!

**Comment by stepio** [comment]
I agree that it's not clear where to merge it as of now, so I'll just keep tracking this issue.

Meanwhile I'll also take a look on Spring Boot's `/health` endpoint - seems that some support for Kafka will be desirable there as well.

**Comment by garyrussell** [comment]
We're adding Kafka support to boot 1.5 

https://github.com/spring-projects/spring-boot/pull/6961

So this probably belongs over there after that is merged.

**Comment by garyrussell** [comment]
Boot autoconfigures Kafka metrics (since 2.1) [here](https://github.com/spring-projects/spring-boot/blob/02fd0c45e436598d9ed62b76b3830929435b85f8/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/KafkaMetricsAutoConfiguration.java#L45-L54).
